import Foundation
import MacNetModels

/// The rendered output: everything dnsmasq will read, and nothing else.
public struct GeneratedDnsmasqConfiguration: Sendable, Equatable {
    public let configurationText: String
    public let hostsText: String

    public init(configurationText: String, hostsText: String) {
        self.configurationText = configurationText
        self.hostsText = hostsText
    }
}

/// Renders a validated request into a dnsmasq configuration file and a hosts file.
///
/// ## Contract (ticket §9.1)
///
/// * **Pure.** No file system, no clock, no environment. Output depends only on the two
///   arguments, which is what makes it exhaustively testable against golden files.
/// * **Deterministic.** Same input, byte-identical output. Sections are emitted in a fixed
///   order and host entries are sorted, so a diff between two runs means a real change.
/// * **Closed.** There is no way for a user to contribute a raw directive. Every line below
///   is written by this file; user input only ever supplies a *value* in a position this code
///   chose, and every such value was validated before `ValidatedSessionRequest` could exist.
/// * **Unix line endings, trailing newline.**
///
/// ## What is deliberately never emitted
///
/// No `conf-file` or `conf-dir`, so the generated file cannot pull in anything else. dnsmasq
/// is launched with `--conf-file=` pointing here, which also stops it reading
/// `/etc/dnsmasq.conf` (ticket §9.9). `no-hosts` stops it reading `/etc/hosts` (ticket §9.8).
/// Between them, the running server's entire configuration is this one generated file.
public struct DnsmasqConfigurationGenerator: Sendable {

    public init() {}

    public func generate(
        request: ValidatedSessionRequest,
        paths: RuntimePaths
    ) -> GeneratedDnsmasqConfiguration {
        GeneratedDnsmasqConfiguration(
            configurationText: makeConfiguration(request: request, paths: paths),
            hostsText: makeHosts(request: request)
        )
    }

    // MARK: - Configuration file

    private func makeConfiguration(
        request: ValidatedSessionRequest,
        paths: RuntimePaths
    ) -> String {
        var sections: [[String]] = []

        sections.append(["# Generated by Dnsmasq for Mac. Do not edit."])
        sections.append(listenerSection(request))

        if request.dns.enabled {
            sections.append(hostsSection(paths))
            if let upstream = upstreamSection(request) { sections.append(upstream) }
            sections.append(dnsBehaviourSection(request))
        } else {
            // Ticket §9.5: port 0 disables DNS entirely while leaving DHCP running.
            sections.append(["port=0"])
        }

        if request.dhcp.enabled {
            sections.append(dhcpSection(request, paths: paths))
        }

        sections.append(loggingSection(request, paths: paths))
        sections.append(privilegeSection())

        // Blank line between sections, single trailing newline at the end.
        return sections.map { $0.joined(separator: "\n") }.joined(separator: "\n\n") + "\n"
    }

    /// Pins dnsmasq to exactly one interface and one address.
    ///
    /// `bind-interfaces` makes dnsmasq open sockets on the named interface instead of
    /// listening on the wildcard address and filtering afterwards. On a machine that is also
    /// on Wi-Fi — the normal case for this product — that is the difference between serving
    /// the bench network and answering the office one.
    private func listenerSection(_ request: ValidatedSessionRequest) -> [String] {
        [
            "interface=\(request.interfaceBSDName)",
            "except-interface=lo0",
            "listen-address=\(request.serverIPv4)",
            "bind-interfaces",
        ]
    }

    private func hostsSection(_ paths: RuntimePaths) -> [String] {
        [
            // Never read the system hosts file (ticket §2.1, §9.8).
            "no-hosts",
            "addn-hosts=\(paths.hostsFile)",
        ]
    }

    /// Upstream resolvers, or nothing in local-only mode.
    ///
    /// `no-resolv` is emitted in every mode, including local-only: without it dnsmasq reads
    /// `/etc/resolv.conf`, which would both consult the system's resolvers behind the user's
    /// back and defeat the point of local-only.
    private func upstreamSection(_ request: ValidatedSessionRequest) -> [String]? {
        var lines = ["no-resolv"]
        lines.append(contentsOf: request.upstreamServers.map { "server=\($0)" })
        return lines
    }

    private func dnsBehaviourSection(_ request: ValidatedSessionRequest) -> [String] {
        var lines = [
            // Do not forward names without a dot; they are never valid public names.
            "domain-needed",
            // Do not forward reverse lookups for private ranges to a public resolver — that
            // leaks the lab's addressing to whoever runs it.
            "bogus-priv",
            // Answer for the local domain authoritatively; never forward it upstream.
            "local=/\(request.normalizedLocalDomain)/",
            "domain=\(request.normalizedLocalDomain)",
            // Let a DHCP client's hostname resolve as name.domain (ticket §2.1).
            "expand-hosts",
            "cache-size=1000",
        ]
        if request.dns.logQueries {
            // `extra` adds a query id and the requesting address, which is what makes the log
            // usable for working out which device asked for what.
            lines.append("log-queries=extra")
        }
        return lines
    }

    private func dhcpSection(
        _ request: ValidatedSessionRequest,
        paths: RuntimePaths
    ) -> [String] {
        var lines: [String] = []

        let lease = Self.formatLeaseDuration(request.dhcp.leaseDurationSeconds)
        lines.append(
            "dhcp-range=\(request.dhcp.rangeStart),\(request.dhcp.rangeEnd),"
                + "\(request.subnet.netmask),\(lease)"
        )

        if request.dhcp.authoritative {
            lines.append("dhcp-authoritative")
        }

        // An option written with no value tells dnsmasq to send that option not at all,
        // suppressing the default it would otherwise derive (ticket §9.3, §9.4).
        if request.dhcp.advertiseRouter, let router = request.dhcp.routerIPv4 {
            lines.append("dhcp-option=option:router,\(router)")
        } else {
            lines.append("dhcp-option=option:router")
        }

        if request.dns.enabled && request.dhcp.advertiseLocalDNSServer {
            lines.append("dhcp-option=option:dns-server,\(request.serverIPv4)")
        } else {
            // Without this, dnsmasq advertises itself as the DNS server by default — which
            // would point clients at a port that is closed.
            lines.append("dhcp-option=option:dns-server")
        }

        if request.dns.enabled {
            lines.append("dhcp-option=option:domain-name,\(request.normalizedLocalDomain)")
        }

        if let poolSize = request.dhcp.poolSize {
            lines.append("dhcp-lease-max=\(poolSize)")
        }
        lines.append("dhcp-leasefile=\(paths.leaseFile)")

        return lines
    }

    private func loggingSection(
        _ request: ValidatedSessionRequest,
        paths: RuntimePaths
    ) -> [String] {
        var lines: [String] = []
        if request.dhcp.enabled {
            // DHCP logging is always on when DHCP is (ticket §2.1): the lease exchange is the
            // single most useful thing to see when a device is not getting an address.
            lines.append("log-dhcp")
        }
        lines.append("log-facility=\(paths.logFile)")
        // Queue log writes so a slow disk cannot stall packet handling.
        lines.append("log-async=25")
        lines.append("pid-file=\(paths.pidFile)")
        return lines
    }

    /// Drops privileges after the sockets are open.
    ///
    /// dnsmasq opens its DHCP, raw, and ICMP sockets while still root and only then calls
    /// `setuid`, so the running server holds no more privilege than it needs. The helper
    /// pre-creates the lease, log, and pid files owned by `nobody` for the same reason: the
    /// session directory itself stays unwritable by the dropped-privilege process.
    private func privilegeSection() -> [String] {
        ["user=nobody", "group=nobody"]
    }

    // MARK: - Hosts file

    /// Renders the additional hosts file (ticket §9.8).
    ///
    /// Entries arrive already sorted and de-duplicated. The record's comment is **not**
    /// written — ticket §7.8 keeps it UI-only precisely so that a comment can never become a
    /// second entry or terminate the line early.
    private func makeHosts(request: ValidatedSessionRequest) -> String {
        guard request.dns.enabled, !request.hostEntries.isEmpty else {
            // dnsmasq is content with an empty addn-hosts file; the helper still creates it so
            // that the path in the config always resolves.
            return ""
        }

        let lines = request.hostEntries.map { entry in
            ([entry.address.description] + entry.names).joined(separator: " ")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Formatting

    /// Formats a lease duration the way dnsmasq's own documentation writes them.
    ///
    /// Emitted in the largest unit that divides evenly — 43200 becomes `12h`, not `43200` —
    /// so the generated file reads the way a person would have written it. dnsmasq accepts
    /// both, but a config a human can check at a glance is worth the few lines.
    static func formatLeaseDuration(_ seconds: Int) -> String {
        if seconds % 86_400 == 0 { return "\(seconds / 86_400)d" }
        if seconds % 3_600 == 0 { return "\(seconds / 3_600)h" }
        if seconds % 60 == 0 { return "\(seconds / 60)m" }
        return "\(seconds)s"
    }
}
