// Generated by Scripts/generate-dnsmasq-hash.sh. Do not edit.
//
// Regenerate with: make vendor-dnsmasq

import Foundation

/// Identity of the dnsmasq build that ships with this version of Dnsmasq for Mac.
///
/// ## What the digest describes
///
/// `expectedSHA256` is the digest of the **unsigned** build artefact — what came out of the
/// compiler, before it was copied into the app bundle and signed. `codesign` embeds the
/// signature inside the Mach-O, so the bundled file's bytes, and therefore its digest, are
/// necessarily different. Comparing the bundled copy against this value could never succeed.
///
/// This digest answers "did we ship the dnsmasq we built?" and is checked by
/// `Scripts/verify-bundle.sh` against `Resources/ThirdParty/dnsmasq/dist/dnsmasq`.
///
/// ## How the binary that actually runs is verified
///
/// Before every launch the helper checks the copy in the bundle for:
///
/// * a valid code signature satisfying a requirement pinned to our Team ID — the same
///   mechanism that authenticates the XPC peer, and stronger than a digest because it proves
///   provenance rather than matching a number that an attacker able to replace the binary
///   could also replace;
/// * being a regular file, not a symlink, and not group- or world-writable;
/// * reporting `version` from `--version`.
///
/// The specification asks for a recomputed SHA-256 at launch. That is not constructible: the
/// helper is compiled before dnsmasq is signed, so no compile-time constant can describe the
/// signed file, and the signing identity differs between Debug and Release. The checks above
/// meet the requirement's intent — refuse to execute a dnsmasq that is not the one we
/// shipped — without depending on a value that cannot exist.
public enum DnsmasqBinaryIdentity: Sendable {
    /// Upstream version string, as reported by `dnsmasq --version`.
    public static let version = "2.93"

    /// SHA-256 of the unsigned Universal 2 executable produced by Scripts/build-dnsmasq.sh.
    public static let expectedSHA256 = "abc4d24d5ccac006fd40efb554f7bfc4e361ab05587db5272fd059bd74f3eea8"

    /// Architecture slices the shipped binary contains.
    public static let architectures = "x86_64 arm64"
}
