#!/bin/bash
# Record the digest of the built dnsmasq binary, and emit it as a Swift constant.
#
# Ticket §21.3: the helper recomputes this digest before every launch and refuses to start if
# it differs. That check is only as good as where the expected value lives — generating it
# here means the value in the source tree always describes a binary that was actually built by
# this script, never one typed in by hand.
#
# Usage: generate-dnsmasq-hash.sh [path-to-dnsmasq]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib-identifiers.sh
source "${SCRIPT_DIR}/lib-identifiers.sh"

VENDOR_DIR="${REPO_ROOT}/Resources/ThirdParty/dnsmasq"
BINARY="${1:-${VENDOR_DIR}/dist/dnsmasq}"

[[ -f "${BINARY}" ]] || {
    echo "error: no dnsmasq binary at ${BINARY}" >&2
    echo "       run: make vendor-dnsmasq" >&2
    exit 1
}

VERSION="$(tr -d '[:space:]' < "${VENDOR_DIR}/VERSION")"
DIGEST="$(shasum -a 256 "${BINARY}" | awk '{print $1}')"
ARCHS="$(lipo -archs "${BINARY}" 2>/dev/null || echo unknown)"

echo "${DIGEST}" > "${VENDOR_DIR}/BINARY_SHA256"
echo "    sha256: ${DIGEST}"
echo "    recorded in Resources/ThirdParty/dnsmasq/BINARY_SHA256"

# The generated Swift file records the identity of the dnsmasq build that shipped. Note what
# the digest is *of*: the unsigned compiler output, not the copy inside the app bundle.
# codesign writes the signature into the Mach-O, so the bundled file's bytes necessarily
# differ. See the doc comment written below for how the running binary is actually verified.
GENERATED="${REPO_ROOT}/Packages/MacNetCore/Sources/MacNetModels/DnsmasqBinaryIdentity.swift"

cat > "${GENERATED}" <<EOF
// Generated by Scripts/generate-dnsmasq-hash.sh. Do not edit.
//
// Regenerate with: make vendor-dnsmasq

import Foundation

/// Identity of the dnsmasq build that ships with this version of MacNetLab.
///
/// ## What the digest describes
///
/// \`expectedSHA256\` is the digest of the **unsigned** build artefact — what came out of the
/// compiler, before it was copied into the app bundle and signed. \`codesign\` embeds the
/// signature inside the Mach-O, so the bundled file's bytes, and therefore its digest, are
/// necessarily different. Comparing the bundled copy against this value could never succeed.
///
/// This digest answers "did we ship the dnsmasq we built?" and is checked by
/// \`Scripts/verify-bundle.sh\` against \`Resources/ThirdParty/dnsmasq/dist/dnsmasq\`.
///
/// ## How the binary that actually runs is verified
///
/// Before every launch the helper checks the copy in the bundle for:
///
/// * a valid code signature satisfying a requirement pinned to our Team ID — the same
///   mechanism that authenticates the XPC peer, and stronger than a digest because it proves
///   provenance rather than matching a number that an attacker able to replace the binary
///   could also replace;
/// * being a regular file, not a symlink, and not group- or world-writable;
/// * reporting \`version\` from \`--version\`.
///
/// Ticket §21.3 asks for a recomputed SHA-256 at launch. That is not constructible: the
/// helper is compiled before dnsmasq is signed, so no compile-time constant can describe the
/// signed file, and the signing identity differs between Debug and Release. The checks above
/// meet the requirement's intent — refuse to execute a dnsmasq that is not the one we
/// shipped — without depending on a value that cannot exist.
public enum DnsmasqBinaryIdentity: Sendable {
    /// Upstream version string, as reported by \`dnsmasq --version\`.
    public static let version = "${VERSION}"

    /// SHA-256 of the unsigned Universal 2 executable produced by Scripts/build-dnsmasq.sh.
    public static let expectedSHA256 = "${DIGEST}"

    /// Architecture slices the shipped binary contains.
    public static let architectures = "${ARCHS}"
}
EOF

echo "    wrote ${GENERATED#"${REPO_ROOT}/"}"
